### ISSUE TITLE
copySupport.mk is Linux only and fails on BSD/MacOS (+ win of course)

### ISSUE THREAD

**Issue by jfabry** [SquareBracketAssociates/BuildingUIWithSpec#13]
`copySupport.mk` relies on the Linux semantics of cp with regard to the `-r` and `--parents` options. This makes the build fail on BSD systems like MacOS (+ windows)
- The easy one first: for BSD `cp -r support/ $(OUTPUTDIRECTORY)` should be `cp -R support $(OUTPUTDIRECTORY)` But I have no clue if this will work on Linux
- Before that, in the find command, this part is never going to work `-exec cp {} --parents -r ${OUTPUTDIRECTORY} \;` because there is no alternative for `--parents`, or at least that I can find. I am not clever enough to change the find command.

@DamienCassou @YannDub @ThibaultAr please please provide a fix for this because I am totally stuck and cannot work on the documentation like this. 

(This is a refinement of issue #11 )

**Comment by YannDub** [comment]
`cp -R support $(OUTPUTDIRECTORY)` works on Linux. For `-exec cp {} --parents -r ${OUTPUTDIRECTORY} \;` maybe will work with -R ?

(edit : I have tested on a Mac and it works but change nothing on the problem)

**Comment by YannDub** [comment]
Ok, I have found the problem, cp was a bad idea because on Linux, it is a POSIX command. I use now `exec rsync -rR {} ${OUTPUTDIRECTORY} \;`. It works on Linux and Mac.

I await your feedback :)

**Comment by jfabry** [comment]
@YannDub yes now it works fine. Thanks a lot !!
